version: '3'

services:
  database:
    image: mariadb:10.3
    ports:
      - '3306:3306'
    environment:
      MARIADB_DATABASE: mysite
      MARIADB_ROOT_PASSWORD: root123
#      MARIADB_USER: test
#      MARIADB_PASSWORD: test123
